const dataTable = [
  {
    Order: 131719,
    Buyer: "Tami 6677",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/22/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7423",
    Archived: ""
  },
  {
    Order: 131705,
    Buyer: "Tim 7591",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/22/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 400,
    Status: "Submitted",
    "Order #": "072219-7399",
    Archived: ""
  },
  {
    Order: 131673,
    Buyer: "Kurt 413518",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/22/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 450,
    Status: "Submitted",
    "Order #": "072219-7353",
    Archived: ""
  },
  {
    Order: 131648,
    Buyer: "Bill 3446",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/22/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 600,
    Status: "Submitted",
    "Order #": "072219-7357",
    Archived: ""
  },
  {
    Order: 131584,
    Buyer: "Kayla 3316",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7372",
    Archived: ""
  },
  {
    Order: 131548,
    Buyer: "Annette 3528",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "072219-7378",
    Archived: ""
  },
  {
    Order: 131543,
    Buyer: "Phil 6759",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7381",
    Archived: ""
  },
  {
    Order: 131541,
    Buyer: "Katie 6798",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7402",
    Archived: ""
  },
  {
    Order: 131540,
    Buyer: "Kurt 8789",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7409",
    Archived: ""
  },
  {
    Order: 131538,
    Buyer: "Amy 7844",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7425",
    Archived: ""
  },
  {
    Order: 131537,
    Buyer: "Steve 4549",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072219-7429",
    Archived: ""
  },
  {
    Order: 131441,
    Buyer: "Elaine 8952",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/19/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 450,
    Status: "Submitted",
    "Order #": "072219-7436",
    Archived: ""
  },
  {
    Order: 131131,
    Buyer: "ALFREDO 6999",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/16/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071619-6619",
    Archived: ""
  },
  {
    Order: 130810,
    Buyer: "Jana 5117",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/12/19",
    "In-Hands Date": "7/26/19",
    "# Line Items": 3,
    "Order $": "1,009.20",
    Status: "Submitted",
    "Order #": "071219-6100",
    Archived: ""
  },
  {
    Order: 130621,
    Buyer: "Janice 4002",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/11/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071119-5749",
    Archived: ""
  },
  {
    Order: 129863,
    Buyer: "Britney 8855",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/3/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070319-4899",
    Archived: ""
  },
  {
    Order: 129862,
    Buyer: "Britney 8855",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/3/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 682.8,
    Status: "Submitted",
    "Order #": "070319-4893",
    Archived: ""
  },
  {
    Order: 129829,
    Buyer: "Dave 6147",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/3/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "070319-4837",
    Archived: ""
  },
  {
    Order: 129828,
    Buyer: "Courtney 413310",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/3/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070319-4839",
    Archived: ""
  },
  {
    Order: 129635,
    Buyer: "Shelly 4336",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/2/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 523.2,
    Status: "Submitted",
    "Order #": "070219-4625",
    Archived: ""
  },
  {
    Order: 129634,
    Buyer: "Robyn 3092",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/2/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 266.4,
    Status: "Submitted",
    "Order #": "070219-4637",
    Archived: ""
  },
  {
    Order: 129633,
    Buyer: "Jill 3116",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/2/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 549.12,
    Status: "Submitted",
    "Order #": "070219-4645",
    Archived: ""
  },
  {
    Order: 129631,
    Buyer: "Brandon 9639",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/2/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 274.56,
    Status: "Submitted",
    "Order #": "070219-4651",
    Archived: ""
  },
  {
    Order: 129630,
    Buyer: "Brandon 9639",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/2/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 266.4,
    Status: "Submitted",
    "Order #": "070219-4654",
    Archived: ""
  },
  {
    Order: 129589,
    Buyer: "Debbie 3178",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 6,
    "Order $": 650,
    Status: "Submitted",
    "Order #": "070219-4657",
    Archived: ""
  },
  {
    Order: 129568,
    Buyer: "STEVE 4176",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4663",
    Archived: ""
  },
  {
    Order: 129473,
    Buyer: "Mark 4633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070919-5427",
    Archived: ""
  },
  {
    Order: 129554,
    Buyer: "Jill 3116",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4671",
    Archived: ""
  },
  {
    Order: 129552,
    Buyer: "Bill 8051",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4672",
    Archived: ""
  },
  {
    Order: 129551,
    Buyer: "Troy 8268",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4675",
    Archived: ""
  },
  {
    Order: 129549,
    Buyer: "Greg 5520",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4679",
    Archived: ""
  },
  {
    Order: 129548,
    Buyer: "Jerilyn 5506",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4689",
    Archived: ""
  },
  {
    Order: 129546,
    Buyer: "Rosie 4770",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4691",
    Archived: ""
  },
  {
    Order: 129544,
    Buyer: "Ron 3633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 307.5,
    Status: "Submitted",
    "Order #": "070219-4702",
    Archived: ""
  },
  {
    Order: 129518,
    Buyer: "Cheryl 2865",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/1/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "070219-4719",
    Archived: ""
  },
  {
    Order: 129468,
    Buyer: "Deb 7970",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 4,
    "Order $": "1,180.00",
    Status: "Submitted",
    "Order #": "070219-4731",
    Archived: ""
  },
  {
    Order: 129467,
    Buyer: "Bob 8728",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4736",
    Archived: ""
  },
  {
    Order: 129465,
    Buyer: "Cheryl 2865",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070219-4725",
    Archived: ""
  },
  {
    Order: 129464,
    Buyer: "Lynn 402008",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 350,
    Status: "Submitted",
    "Order #": "070219-4740",
    Archived: ""
  },
  {
    Order: 129463,
    Buyer: "Lynn 402008",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 750,
    Status: "Submitted",
    "Order #": "070219-4746",
    Archived: ""
  },
  {
    Order: 129456,
    Buyer: "Allen 6718",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/30/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": "1,000.00",
    Status: "Submitted",
    "Order #": "070219-4750",
    Archived: ""
  },
  {
    Order: 129442,
    Buyer: "Tom Z 7888",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 4,
    "Order $": "1,000.00",
    Status: "Submitted",
    "Order #": "070219-4756",
    Archived: ""
  },
  {
    Order: 129437,
    Buyer: "STEVE 4176",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 97.5,
    Status: "Submitted",
    "Order #": "070319-4850",
    Archived: ""
  },
  {
    Order: 129434,
    Buyer: "Bill 8051",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 6,
    "Order $": 650,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 129433,
    Buyer: "Diane 1744",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070319-4875",
    Archived: ""
  },
  {
    Order: 129431,
    Buyer: "Jim 4978",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 4,
    "Order $": 600,
    Status: "Submitted",
    "Order #": "070319-4909",
    Archived: ""
  },
  {
    Order: 129427,
    Buyer: "Jason 2915",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070319-4917",
    Archived: ""
  },
  {
    Order: 129426,
    Buyer: "Deanna 6932",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070319-4930",
    Archived: ""
  },
  {
    Order: 129425,
    Buyer: "Pat 7505",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 400,
    Status: "Submitted",
    "Order #": "070319-4937",
    Archived: ""
  },
  {
    Order: 129424,
    Buyer: "MIKE 3129",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 217.5,
    Status: "Submitted",
    "Order #": "070919-5434",
    Archived: ""
  },
  {
    Order: 129334,
    Buyer: "Ryan 9754",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "070919-5443",
    Archived: ""
  },
  {
    Order: 129417,
    Buyer: "David 6429",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/29/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 480,
    Status: "Submitted",
    "Order #": "070919-5453",
    Archived: ""
  },
  {
    Order: 129391,
    Buyer: "Robyn 3092",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5517",
    Archived: ""
  },
  {
    Order: 129387,
    Buyer: "KAREN 7138",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 97.5,
    Status: "Pending",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 129384,
    Buyer: "KAREN 7138",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 5,
    "Order $": 550,
    Status: "Submitted",
    "Order #": "071019-5527",
    Archived: ""
  },
  {
    Order: 129362,
    Buyer: "Allan 9106",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5530",
    Archived: ""
  },
  {
    Order: 129356,
    Buyer: "Laura 425207",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5535",
    Archived: ""
  },
  {
    Order: 129354,
    Buyer: "Carinna 4831",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5538",
    Archived: ""
  },
  {
    Order: 129352,
    Buyer: "Ryan 3461",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5543",
    Archived: ""
  },
  {
    Order: 129351,
    Buyer: "Timothy 7724",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5548",
    Archived: ""
  },
  {
    Order: 129350,
    Buyer: "Paul 4317",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5546",
    Archived: ""
  },
  {
    Order: 129338,
    Buyer: "Jeff 1529",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5553",
    Archived: ""
  },
  {
    Order: 106614,
    Buyer: "Jodi 1578",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5557",
    Archived: ""
  },
  {
    Order: 129293,
    Buyer: "Steve 3188",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 312,
    Status: "Submitted",
    "Order #": "071219-6093",
    Archived: ""
  },
  {
    Order: 129290,
    Buyer: "Andrea 6454",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5563",
    Archived: ""
  },
  {
    Order: 129286,
    Buyer: "Steve 3188",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5569",
    Archived: ""
  },
  {
    Order: 129283,
    Buyer: "Joe 461343",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "071019-5574",
    Archived: ""
  },
  {
    Order: 129282,
    Buyer: "Larry 9072",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5579",
    Archived: ""
  },
  {
    Order: 129279,
    Buyer: "Apr-62",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5581",
    Archived: ""
  },
  {
    Order: 129278,
    Buyer: "Matt 4032",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 600,
    Status: "Submitted",
    "Order #": "071019-5583",
    Archived: ""
  },
  {
    Order: 129277,
    Buyer: "Brad 3735",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071019-5586",
    Archived: ""
  },
  {
    Order: 129266,
    Buyer: "Dan 6537",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/28/19",
    "In-Hands Date": "10/30/19",
    "# Line Items": 6,
    "Order $": "1,200.00",
    Status: "Submitted",
    "Order #": "070119-4442",
    Archived: ""
  },
  {
    Order: 120752,
    Buyer: "Mark 4633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/1/19",
    "In-Hands Date": "5/17/19",
    "# Line Items": 1,
    "Order $": 156,
    Status: "Submitted",
    "Order #": "050219-3303",
    Archived: ""
  },
  {
    Order: 49749,
    Buyer: "Tim Craig",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "4/23/19",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 300,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 115196,
    Buyer: "Wayne 9340",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "3/22/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "032219-4824",
    Archived: ""
  },
  {
    Order: 113789,
    Buyer: "Kelly 3164",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "3/12/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 82.5,
    Status: "Submitted",
    "Order #": "031319-2847",
    Archived: ""
  },
  {
    Order: 112224,
    Buyer: "Roger 3343",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/28/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": "1,250.00",
    Status: "Submitted",
    "Order #": "022819-0461",
    Archived: ""
  },
  {
    Order: 111316,
    Buyer: "Eric 6286",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/20/19",
    "In-Hands Date": "3/8/19",
    "# Line Items": 1,
    "Order $": 192,
    Status: "Submitted",
    "Order #": "022019-8769",
    Archived: ""
  },
  {
    Order: 107523,
    Buyer: "Mark 4633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/21/19",
    "In-Hands Date": "2/5/19",
    "# Line Items": 2,
    "Order $": 378,
    Status: "Submitted",
    "Order #": "012219-3996",
    Archived: ""
  },
  {
    Order: 106606,
    Buyer: "Pat 7505",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/12/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 363,
    Status: "Submitted",
    "Order #": "012319-4212",
    Archived: ""
  },
  {
    Order: 106599,
    Buyer: "Trish 1692",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/12/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 201,
    Status: "Submitted",
    "Order #": "012319-4210",
    Archived: ""
  },
  {
    Order: 106595,
    Buyer: "Wayne 4159",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/12/19",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 196,
    Status: "Submitted",
    "Order #": "012119-3787",
    Archived: ""
  },
  {
    Order: 95381,
    Buyer: "Cheryl 2865",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "10/2/18",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 96.36,
    Status: "Submitted",
    "Order #": "100218-4711",
    Archived: ""
  },
  {
    Order: 94808,
    Buyer: "Julie 3422",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "9/26/18",
    "In-Hands Date": "9/28/18",
    "# Line Items": 1,
    "Order $": 18,
    Status: "Pending",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 94793,
    Buyer: "Darla 599043",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "9/26/18",
    "In-Hands Date": "12/10/18",
    "# Line Items": 2,
    "Order $": 362,
    Status: "Submitted",
    "Order #": "092718-3808",
    Archived: ""
  },
  {
    Order: 88816,
    Buyer: "Jon 6395",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "8/7/18",
    "In-Hands Date": "10/31/18",
    "# Line Items": 2,
    "Order $": 600,
    Status: "Submitted",
    "Order #": "080718-3643",
    Archived: ""
  },
  {
    Order: 88192,
    Buyer: "Lisa 1115",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "8/1/18",
    "In-Hands Date": "10/1/18",
    "# Line Items": 1,
    "Order $": 80.4,
    Status: "Pending",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 81020,
    Buyer: "LuBell 5835",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/24/18",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 38.5,
    Status: "Submitted",
    "Order #": "052418-1006",
    Archived: ""
  },
  {
    Order: 73494,
    Buyer: "Jon 6395",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/21/18",
    "In-Hands Date": "6/18/18",
    "# Line Items": 4,
    "Order $": "1,257.00",
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 78995,
    Buyer: "Kayla 8594",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/8/18",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 264,
    Status: "Submitted",
    "Order #": "050818-7569",
    Archived: ""
  },
  {
    Order: 69586,
    Buyer: "Dan 6161",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/16/18",
    "In-Hands Date": "",
    "# Line Items": 3,
    "Order $": 539.5,
    Status: "Submitted",
    "Order #": "021618-9176",
    Archived: ""
  },
  {
    Order: 55042,
    Buyer: "Brad 3735",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "10/19/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 468,
    Status: "Submitted",
    "Order #": "101917-1917",
    Archived: ""
  },
  {
    Order: 58342,
    Buyer: "Phil 6759",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "10/18/17",
    "In-Hands Date": "11/1/17",
    "# Line Items": 1,
    "Order $": 112.5,
    Status: "Submitted",
    "Order #": "101817-1689",
    Archived: ""
  },
  {
    Order: 57043,
    Buyer: "Joyce 8425",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "10/6/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 484.3,
    Status: "Submitted",
    "Order #": "101617-1206",
    Archived: ""
  },
  {
    Order: 54280,
    Buyer: "Joyce 8425",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "9/11/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 346.5,
    Status: "Submitted",
    "Order #": "091217-5622",
    Archived: ""
  },
  {
    Order: 52896,
    Buyer: "Joyce 8425",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "8/25/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": "1,170.60",
    Status: "Submitted",
    "Order #": "082517-3244",
    Archived: ""
  },
  {
    Order: 49868,
    Buyer: "Greg 5520",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/24/17",
    "In-Hands Date": "10/2/17",
    "# Line Items": 2,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "072417-8134",
    Archived: ""
  },
  {
    Order: 48812,
    Buyer: "Roxy 400069",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/13/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 112.5,
    Status: "Submitted",
    "Order #": "071317-6247",
    Archived: ""
  },
  {
    Order: 48648,
    Buyer: "Matt 4032",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "7/12/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "Submitted",
    "Order #": "071217-6076",
    Archived: ""
  },
  {
    Order: 45916,
    Buyer: "Apr-62",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "6/8/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 112.5,
    Status: "Submitted",
    "Order #": "060817-2124",
    Archived: ""
  },
  {
    Order: 44386,
    Buyer: "Jonathan Carver",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/24/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 165,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 32794,
    Buyer: "Joel 7144",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/2/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 215,
    Status: "Submitted",
    "Order #": "051017-7697",
    Archived: ""
  },
  {
    Order: 42096,
    Buyer: "Ladd 7678",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "5/1/17",
    "In-Hands Date": "5/15/17",
    "# Line Items": 3,
    "Order $": 442.5,
    Status: "Submitted",
    "Order #": "050117-6397",
    Archived: ""
  },
  {
    Order: 41611,
    Buyer: "Rick 6703",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "4/25/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 112.5,
    Status: "Submitted",
    "Order #": "052417-0038",
    Archived: ""
  },
  {
    Order: 41588,
    Buyer: "Tami 6677",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "4/25/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 200,
    Status: "Submitted",
    "Order #": "042517-5678",
    Archived: ""
  },
  {
    Order: 40193,
    Buyer: "Kayla 3316",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "4/7/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 171,
    Status: "Submitted",
    "Order #": "040717-3361",
    Archived: ""
  },
  {
    Order: 32797,
    Buyer: "Mark 4633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "3/28/17",
    "In-Hands Date": "1/26/17",
    "# Line Items": 1,
    "Order $": 175.92,
    Status: "Submitted",
    "Order #": "032817-1701",
    Archived: ""
  },
  {
    Order: 37217,
    Buyer: "Kathy 3142",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "3/2/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 150,
    Status: "Submitted",
    "Order #": "030217-7683",
    Archived: ""
  },
  {
    Order: 32798,
    Buyer: "Tim Craig",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/16/17",
    "In-Hands Date": "2/28/17",
    "# Line Items": 1,
    "Order $": 243.48,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 36166,
    Buyer: "Deborah 6122",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/16/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 175.62,
    Status: "Submitted",
    "Order #": "021717-6070",
    Archived: ""
  },
  {
    Order: 35146,
    Buyer: "Troy 8268",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/6/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 350.55,
    Status: "Submitted",
    "Order #": "020617-4555",
    Archived: ""
  },
  {
    Order: 32804,
    Buyer: "Krista Maurer",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "2/1/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 165,
    Status: "Submitted",
    "Order #": "020117-4102",
    Archived: ""
  },
  {
    Order: 34079,
    Buyer: "Jim Gildner",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/23/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 396.45,
    Status: "Submitted",
    "Order #": "012317-2756",
    Archived: ""
  },
  {
    Order: 32229,
    Buyer: "Jon 6395",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/16/17",
    "In-Hands Date": "",
    "# Line Items": 4,
    "Order $": "1,165.00",
    Status: "Initiated",
    "Order #": "011617-1815",
    Archived: ""
  },
  {
    Order: 33009,
    Buyer: "Ben Andersen",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/10/17",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 165,
    Status: "Submitted",
    "Order #": "011617-1842",
    Archived: ""
  },
  {
    Order: 32799,
    Buyer: "Krista Maurer",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/8/17",
    "In-Hands Date": "1/25/17",
    "# Line Items": 3,
    "Order $": 340.02,
    Status: "Submitted",
    "Order #": "010917-1124",
    Archived: ""
  },
  {
    Order: 32796,
    Buyer: "Mark 4633",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/7/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 233.4,
    Status: "Submitted",
    "Order #": "010917-1117",
    Archived: ""
  },
  {
    Order: 32795,
    Buyer: "Pat 7505",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "1/7/17",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 233.4,
    Status: "Submitted",
    "Order #": "010917-1113",
    Archived: ""
  },
  {
    Order: 31944,
    Buyer: "Jake 2581",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "12/22/16",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 156,
    Status: "Submitted",
    "Order #": "122216-9156",
    Archived: ""
  },
  {
    Order: 29246,
    Buyer: "Dan 6537",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/15/16",
    "In-Hands Date": "11/30/16",
    "# Line Items": 3,
    "Order $": "1,144.51",
    Status: "Submitted",
    "Order #": "111516-5036",
    Archived: ""
  },
  {
    Order: 122,
    Buyer: "Tim A Craig",
    Store: "Hormel Foods",
    Account: "Hormel Foods Corporation",
    "Checkout Date": "1/15/15",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 209,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 93,
    Buyer: "Jack Link",
    Store: "Jack Links",
    Account: "JACK LINK'S",
    "Checkout Date": "12/1/14",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 540,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 74,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/26/14",
    "# Line Items": 1,
    "Order $": 269.91,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 73,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/26/14",
    "# Line Items": 1,
    "Order $": 269.91,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 72,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/26/14",
    "# Line Items": 1,
    "Order $": 269.91,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 71,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 269.91,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 70,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/26/14",
    "# Line Items": 1,
    "Order $": 269.91,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 69,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 72,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 68,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/25/14",
    "# Line Items": 1,
    "Order $": "1,080.00",
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 67,
    Buyer: "Store # 6395 ,",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "11/11/14",
    "In-Hands Date": "11/25/14",
    "# Line Items": 1,
    "Order $": 539.82,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 75900,
    Buyer: "Chance Hammar",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 266.4,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 44544,
    Buyer: "Jonathan Carver",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 399.9,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 49785,
    Buyer: "Jessica 3029",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 305,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 36559,
    Buyer: "Tim Craig",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 307.5,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 82,
    Buyer: "Jim 4978",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "12/11/14",
    "# Line Items": 1,
    "Order $": 162.5,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 112668,
    Buyer: "Patrick 411058",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 66.5,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 29744,
    Buyer: "Brenda 415976",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": "2,695.16",
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 106602,
    Buyer: "Scott 6611",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 0,
    "Order $": "",
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 24348,
    Buyer: "KENT Knitt",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 490,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 59373,
    Buyer: "Timothy 2817",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 175.62,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 106597,
    Buyer: "Kayla 8594",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 2,
    "Order $": 623,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 493,
    Buyer: "Lion Tim Craig",
    Store: "Lions Clubs International",
    Account: "Carver Lions Club",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 380.75,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 41188,
    Buyer: "Brandon 9639",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 289,
    Status: "Cancelled",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 63729,
    Buyer: "Tim 2162",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 165,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: 89624,
    Buyer: "Clif 5154",
    Store: "1 United Hardware Dist Store",
    Account: "United Hardware Dist. Co.",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": 1,
    "Order $": 300,
    Status: "In-Cart",
    "Order #": "",
    Archived: ""
  },
  {
    Order: "TOTAL $",
    Buyer: "54,961.89",
    Store: "",
    Account: "",
    "Checkout Date": "",
    "In-Hands Date": "",
    "# Line Items": "",
    "Order $": "",
    Status: "",
    "Order #": "",
    Archived: ""
  }
];
